include: package:flutter_lints/flutter.yaml

# mz_lints plugin is available for local development
# To enable, uncomment the plugins section below and ensure mz_lints is available
# plugins:
#   mz_lints:
#     path: ../../mz_lints
